### ISSUE TITLE
Executing error: TypeError: '_ImageAccessor' object is not callable

### ISSUE THREAD

**Issue by homurachan** [yunpeng-shi/fast-cryoEM-PCA#1]
When I tried to execute the demo_synthetic_data_white_noise.py, This error popped up.

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/aspire_env/lib/python3.8/site-packages/aspire/exceptions.py", line 87, in handle_exception
    raise exc_value
  File "./demo_synthetic_data_white_noise.py", line 94, in <module>
    noise_var = utils.get_noise_var_batch(source_ctf_clean, sn_ratio, batch_size)
  File "/home/user/Fast_cryoem_PCA/fast-cryoEM-PCA-main/utils_cwf_fast_batch.py", line 90, in get_noise_var_batch
    imgs_ctf_clean_k = source.images(start=batch_start[k], num=batch_size_list[k])
TypeError: '_ImageAccessor' object is not callable

I also tried the modified demo_experimental_data_10081.py (to use my own data), and error also occurred.

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/aspire_env/lib/python3.8/site-packages/aspire/exceptions.py", line 87, in handle_exception
    raise exc_value
  File "./demo_test.py", line 67, in <module>
    results = fast_pca.denoise_images(denoise_options=denoise_options)
  File "/home/user/Fast_cryoem_PCA/fast-cryoEM-PCA-main/fast_cryo_pca.py", line 493, in denoise_images
    mean_est, covar_est = self.estimate_mean_covar()
  File "/home/user/Fast_cryoem_PCA/fast-cryoEM-PCA-main/fast_cryo_pca.py", line 201, in estimate_mean_covar
    imgs_noise_l = -self.src.images(start=batch_start[l], num=batch_size_list[l]).asnumpy()
TypeError: '_ImageAccessor' object is not callable

Here is the aspire.err.log.
[aspire.err.log](https://github.com/yunpeng-shi/fast-cryoEM-PCA/files/10967018/aspire.err.log)

**Comment by yunpeng-shi** [comment]
Thanks for letting me know. The current code is compatible with ASPIRE v0.9.2 and before, and recently v0.10.0 is released. To make the current code compatible with the new APSIRE version, make the following global change:

replace    .images(start=a, num=b)    by   .images[a:a+b]

be careful that "( )" needs to be changed to "[ ]"

**Comment by homurachan** [comment]
Thanks! I installed ASPIRE v0.9.2 and ran without problem.
